### ISSUE TITLE
Virtual desktop speed animation and preview 

### ISSUE THREAD

**Issue by Fujitora100** [linuxdeepin/dde-desktop#52]
hi, would there be a way to hide the preview of the virtual desktop switch? and speed up desktop switch animation?
this preview: 
![58978674-9e465b80-87cc-11e9-8241-d6fc5109af18](https://user-images.githubusercontent.com/51417982/59259594-66ab3980-8c3a-11e9-9f7f-239b876f179e.jpg)

**Comment by BLumia** [comment]
If you are using dde-kwin from Deepin distro (or maybe it named deepin-kwin in other distro), you actually can tweak some kwin setting by install `systemsettings` package.

Closing since it's not an issue of `dde-desktop` package. Feel free to post your issue to [Developer Center](https://github.com/linuxdeepin/developer-center/issues) with detail information provided if you have any other issue.
